### PR TITLE
ci: new docker image release setup

### PR DESCRIPTION
**Pull request by codfish**

### CODE REVIEW

**Comment by iAmMichaelConnor** [comment]
@codfish @ocgordon @alexcoury many thanks for this!

What are the implications of this change for non-EY people wanting to use Timber (or Nightfall, which uses Timber)? We previously had this 'installation' info in the README:

"
Github Configuration

In order to use Nightfall, you will need to be *logged into the Github package registry*. To do this, you will need to generate a Github Personal Access Token. Make sure that the token you generate has at minimum read: packages and repo permissions.

After you've done that, log in to the Github package registry by running

`docker login -u <your-username> -p <the-token-you-just-generated> docker.pkg.github.com`
"

*Question*: Do users still have to create a Github PAT? In particular, are there any extra steps for non-EY users? And should the above README wording be altered at all (or removed entirely)?

**Comment by iAmMichaelConnor** [comment]
@codfish follow-up question:

I notice there is only a tagged v1.3.0 here: https://hub.docker.com/r/eyblockchain/timber/tags 

The latest tag in this repo is v2.0.0. Does that mean a tag of v2.0.0 hasn't been published to https://hub.docker.com/r/eyblockchain/timber/tags? (or is the packaged labelled 'latest' v2.0.0?)

Many thanks!

**Comment by alexcoury** [comment]
> @codfish @ocgordon @alexcoury many thanks for this!
> 
> What are the implications of this change for non-EY people wanting to use Timber (or Nightfall, which uses Timber)? We previously had this 'installation' info in the README:
> 
> "
> Github Configuration
> 
> In order to use Nightfall, you will need to be _logged into the Github package registry_. To do this, you will need to generate a Github Personal Access Token. Make sure that the token you generate has at minimum read: packages and repo permissions.
> 
> After you've done that, log in to the Github package registry by running
> 
> `docker login -u <your-username> -p <the-token-you-just-generated> docker.pkg.github.com`
> "
> 
> _Question_: Do users still have to create a Github PAT? In particular, are there any extra steps for non-EY users? And should the above README wording be altered at all (or removed entirely)?

@iAmMichaelConnor The Github personal access token is no longer needed now since we are using dockerhub now. The README can be updated to remove this section as well.

**Comment by alexcoury** [comment]
@ocgordon is currently working on updating the README and github actions @iAmMichaelConnor https://github.com/EYBlockchain/nightfall/pull/385/files

**Pull request merged**
